# -*- coding: utf-8 -*-
"""Kidney_stone

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mI7gjiU4_RrNLD7JzSffTL1mn3SddJ7p
"""

print("jhai shrtee ram")



import kagglehub

# Download latest version
path = kagglehub.dataset_download("nazmul0087/ct-kidney-dataset-normal-cyst-tumor-and-stone")

print("Path to dataset files:", path)

import os

root = "/kaggle/input/ct-kidney-dataset-normal-cyst-tumor-and-stone"

for r, d, f in os.walk(root):
    print("DIR:", r)
    print("SUBDIRS:", d)
    print("FILES:", f[:5])
    print("----")
    break

REAL_ROOT = "/kaggle/input/ct-kidney-dataset-normal-cyst-tumor-and-stone/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone"

from pathlib import Path
from PIL import Image
import matplotlib.pyplot as plt

# Correct dataset folder
DATASET_PATH = Path("/kaggle/input/ct-kidney-dataset-normal-cyst-tumor-and-stone/"
                    "CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone")

# List classes
classes = sorted([d.name for d in DATASET_PATH.iterdir() if d.is_dir()])
print("Classes:", classes)

# Collect image paths and labels
image_paths, labels = [], []
for cls in classes:
    for img_file in (DATASET_PATH / cls).glob("*.jpg"):
        image_paths.append(img_file)
        labels.append(cls)

print("Total images:", len(image_paths))
print("Samples per class:")
for cls in classes:
    print(cls, sum([1 for l in labels if l==cls]))

# Display first 10 images
plt.figure(figsize=(20, 6))
for i in range(min(10, len(image_paths))):
    img = Image.open(image_paths[i]).convert("RGB")
    plt.subplot(2, 5, i + 1)
    plt.imshow(img)
    plt.title(labels[i])
    plt.axis("off")
plt.show()

import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
from pathlib import Path

# -------------------- DATASET CLASS --------------------
class KidneyDataset(Dataset):
    def __init__(self, root_dir, classes, transform=None):
        self.root_dir = Path(root_dir)
        self.classes = classes
        self.transform = transform

        self.image_paths = []
        self.labels = []

        for idx, cls in enumerate(classes):
            cls_path = self.root_dir / cls
            for img_file in cls_path.glob("*.jpg"):
                self.image_paths.append(img_file)
                self.labels.append(idx)

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        label = self.labels[idx]

        img = Image.open(img_path).convert("RGB")
        if self.transform:
            img = self.transform(img)

        return img, label


# -------------------- TRANSFORMS --------------------
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

val_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

# -------------------- DATASET + DATALOADER --------------------
ROOT = "/kaggle/input/ct-kidney-dataset-normal-cyst-tumor-and-stone/" \
       "CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone"

classes = ["Normal", "Cyst", "Tumor", "Stone"]

# Split manually (80% train, 20% val)
from sklearn.model_selection import train_test_split

all_images = []
all_labels = []

for idx, cls in enumerate(classes):
    cls_path = Path(ROOT) / cls
    for img_file in cls_path.glob("*.jpg"):
        all_images.append(img_file)
        all_labels.append(idx)

train_imgs, val_imgs, train_lbls, val_lbls = train_test_split(
    all_images, all_labels, test_size=0.2, stratify=all_labels, random_state=42
)

# Custom dataset with preselected files
class SplitKidneyDataset(Dataset):
    def __init__(self, image_paths, labels, transform=None):
        self.image_paths = image_paths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img = Image.open(self.image_paths[idx]).convert("RGB")
        if self.transform:
            img = self.transform(img)
        label = self.labels[idx]
        return img, label

BATCH_SIZE = 32
NUM_WORKERS = 2

train_ds = SplitKidneyDataset(train_imgs, train_lbls, transform=train_transform)
val_ds   = SplitKidneyDataset(val_imgs, val_lbls, transform=val_transform)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS)
val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)

print(f"Train samples: {len(train_ds)} | Val samples: {len(val_ds)}")

# Display first 10 images from training set
import matplotlib.pyplot as plt

plt.figure(figsize=(20,6))
for i in range(10):
    img, lbl = train_ds[i]
    img = img.permute(1, 2, 0).numpy()
    img = img * [0.229, 0.224, 0.225] + [0.485, 0.456, 0.406]  # denormalize
    img = img.clip(0,1)
    plt.subplot(2,5,i+1)
    plt.imshow(img)
    plt.title(classes[lbl])
    plt.axis('off')
plt.show()

import torch
import torch.nn as nn
from torchvision import models

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
NUM_CLASSES = 4   # Normal, Cyst, Tumor, Stone

# ----------------- TRANSFER LEARNING RESNET -----------------
def get_finetune_resnet18(num_classes=NUM_CLASSES):
    # Load pretrained ResNet18
    model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)

    # Freeze early layers (conv1, layer1), unfreeze layers 2,3,4 for fine-tuning
    for name, param in model.named_parameters():
        if "layer2" in name or "layer3" in name or "layer4" in name or "fc" in name:
            param.requires_grad = True
        else:
            param.requires_grad = False

    # Replace the fully connected layer
    in_features = model.fc.in_features
    model.fc = nn.Sequential(
        nn.Linear(in_features, 256),
        nn.ReLU(),
        nn.Dropout(0.3),
        nn.Linear(256, num_classes)
    )

    return model.to(DEVICE)

# Instantiate model
model = get_finetune_resnet18()
print(model)

# ----------------- OPTIMIZER & LOSS -----------------
import torch.optim as optim

# Only train parameters that require grad
optimizer = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=1e-4)
criterion = nn.CrossEntropyLoss()

import torch.optim as optim
criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.fc.parameters(),   # only training last layers
    lr=1e-3,
    weight_decay=1e-4
)

import torch
import os

# ----------------- EPOCH FUNCTIONS -----------------
def train_epoch(loader, model, criterion, optimizer, device):
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    for imgs, labels in loader:
        imgs, labels = imgs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(imgs)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        _, preds = torch.max(outputs, 1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    return total_loss / len(loader), correct / total


def eval_epoch(loader, model, criterion, device):
    model.eval()
    total_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():
        for imgs, labels in loader:
            imgs, labels = imgs.to(device), labels.to(device)

            outputs = model(imgs)
            loss = criterion(outputs, labels)

            total_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    return total_loss / len(loader), correct / total

print("done!")
# ----------------- TRAINING LOOP WITH CHECKPOINT -----------------
checkpoint_dir = "/content/kidney_checkpoints"
os.makedirs(checkpoint_dir, exist_ok=True)

EPOCHS = 15

for epoch in range(1, EPOCHS + 1):
    train_loss, train_acc = train_epoch(train_loader, model, criterion, optimizer, DEVICE)
    val_loss, val_acc = eval_epoch(val_loader, model, criterion, DEVICE)

    print(f"Epoch {epoch}/{EPOCHS}")
    print(f"  Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f}")
    print(f"  Val   Loss: {val_loss:.4f} | Val   Acc: {val_acc:.4f}")

    # Save checkpoint every 3 epochs
    if epoch % 3 == 0:
        checkpoint_path = os.path.join(checkpoint_dir, f"resnet18_epoch{epoch}.pth")
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'train_loss': train_loss,
            'val_loss': val_loss,
            'train_acc': train_acc,
            'val_acc': val_acc
        }, checkpoint_path)
        print(f"Checkpoint saved at {checkpoint_path}")

# Directory to save models
os.makedirs("/content/kidney_checkpoints", exist_ok=True)

# Save model weights
model_path = "/content/kidney_checkpoints/best_model.pth"
torch.save(model.state_dict(), model_path)
print(f"Model weights saved at {model_path}")

import torch
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Set model to evaluation mode
model.eval()

all_preds = []
all_labels = []

# Disable gradients for evaluation
with torch.no_grad():
    for imgs, labels in val_loader:
        imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)
        outputs = model(imgs)
        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# Convert to numpy arrays
all_preds = np.array(all_preds)
all_labels = np.array(all_labels)

# 1️⃣ Overall accuracy
accuracy = (all_preds == all_labels).mean()
print(f"Validation Accuracy: {accuracy:.4f}")

# 2️⃣ Confusion matrix
cm = confusion_matrix(all_labels, all_preds)
print("Confusion Matrix:\n", cm)

# Plot confusion matrix
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=classes, yticklabels=classes)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# 3️⃣ Classification report (precision, recall, F1-score)
report = classification_report(all_labels, all_preds, target_names=classes)
print("Classification Report:\n", report)

import os

checkpoint_dir = "/content/drive/MyDrive/Saved models"
os.makedirs(checkpoint_dir, exist_ok=True)

EPOCHS = 30
START_EPOCH = 16
best_val_acc = 0.0

for epoch in range(START_EPOCH, EPOCHS + 1):
    train_loss, train_acc = train_epoch(train_loader, model, criterion, optimizer, DEVICE)
    val_loss, val_acc = eval_epoch(val_loader, model, criterion, DEVICE)

    print(f"Epoch {epoch}/{EPOCHS}")
    print(f"  Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f}")
    print(f"  Val   Loss: {val_loss:.4f} | Val   Acc: {val_acc:.4f}")

import torch
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Set model to evaluation mode
model.eval()

all_preds = []
all_labels = []

# Disable gradients for evaluation
with torch.no_grad():
    for imgs, labels in val_loader:
        imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)
        outputs = model(imgs)
        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# Convert to numpy arrays
all_preds = np.array(all_preds)
all_labels = np.array(all_labels)

# 1️⃣ Overall accuracy
accuracy = (all_preds == all_labels).mean()
print(f"Validation Accuracy: {accuracy:.4f}")

# 2️⃣ Confusion matrix
cm = confusion_matrix(all_labels, all_preds)
print("Confusion Matrix:\n", cm)

# Plot confusion matrix
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=classes, yticklabels=classes)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# 3️⃣ Classification report (precision, recall, F1-score)
report = classification_report(all_labels, all_preds, target_names=classes)
print("Classification Report:\n", report)

import os
import torch

# Make sure the folder exists
save_path = "/content/drive/MyDrive/Saved models"
os.makedirs(save_path, exist_ok=True)

# Full path to save the model
model_path = os.path.join(save_path, "kidney_model_2.pth")

# Save only the model weights
torch.save(model.state_dict(), model_path)

print(f"Model saved successfully at {model_path}")

"""# Task
Balance the training dataset by oversampling minority classes to match the size of the majority class, then retrain the ResNet18 model for 15 epochs using the balanced dataset, and finally evaluate the model's performance on the validation set by displaying the accuracy, confusion matrix, and classification report. Summarize the improvements in model performance and class-wise accuracy after implementing data balancing.

## Analyze Training Set Class Distribution

### Subtask:
Calculate the current number of samples for each class within the training dataset (`train_lbls`) to identify minority and majority classes.

**Reasoning**:
To analyze the training set class distribution, I will use the `Counter` class from the `collections` module to count the occurrences of each class label in `train_lbls` and then map these numerical labels to their corresponding class names for clear interpretation.
"""

from collections import Counter

# Count occurrences of each class label in train_lbls
class_counts = Counter(train_lbls)

print("Training set class distribution:")
for label_idx, count in class_counts.items():
    class_name = classes[label_idx]
    print(f"  {class_name}: {count} samples")

"""**Reasoning**:
To balance the training dataset, I will use `RandomOverSampler` to oversample the minority classes to match the count of the majority class, which is 'Normal' with 4061 samples. This will create a balanced dataset for training.


"""

from imblearn.over_sampling import RandomOverSampler
import numpy as np

# Find the majority class count
class_counts = Counter(train_lbls)
majority_class_count = max(class_counts.values())

# Define the sampling strategy to oversample all classes to the majority class count
sampling_strategy = {label: majority_class_count for label, count in class_counts.items()}

# Initialize RandomOverSampler
ros = RandomOverSampler(sampling_strategy=sampling_strategy, random_state=42)

# Convert image paths and labels to numpy arrays for oversampling
train_imgs_np = np.array(train_imgs).reshape(-1, 1)
train_lbls_np = np.array(train_lbls)

# Apply oversampling to the training data
train_imgs_resampled, train_lbls_resampled = ros.fit_resample(train_imgs_np, train_lbls_np)

# Convert back to list of PosixPath objects and list of integers
train_imgs_resampled = [Path(p[0]) for p in train_imgs_resampled]
train_lbls_resampled = train_lbls_resampled.tolist()

print("Training set class distribution after oversampling:")
for label_idx, count in Counter(train_lbls_resampled).items():
    class_name = classes[label_idx]
    print(f"  {class_name}: {count} samples")

# Build oversampled dataset
oversampled_train_ds = SplitKidneyDataset(
    train_imgs_resampled,
    train_lbls_resampled,
    transform=train_transform
)

# DataLoader
oversampled_train_loader = DataLoader(
    oversampled_train_ds,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS
)

print("Final balanced class counts:")
for label_idx, count in Counter(train_lbls_resampled).items():
    print(f"  {classes[label_idx]}: {count}")

# Training loop
EPOCHS = 50
START_EPOCH = 16

for epoch in range(START_EPOCH, EPOCHS + 1):
    train_loss, train_acc = train_epoch(
        oversampled_train_loader, model, criterion, optimizer, DEVICE
    )

    val_loss, val_acc = eval_epoch(
        val_loader, model, criterion, DEVICE
    )

    print(f"Epoch {epoch}/{EPOCHS}")
    print(f"  Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f}")
    print(f"  Val   Loss: {val_loss:.4f} | Val   Acc: {val_acc:.4f}")

import os
import torch

# Make sure the folder exists
save_path = "/content/drive/MyDrive/Saved models"
os.makedirs(save_path, exist_ok=True)

# Full path to save the model
model_path = os.path.join(save_path, "kidney_model_final.pth")

# Save only the model weights
torch.save(model.state_dict(), model_path)

print(f"Model saved successfully at {model_path}")

import torch
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Set model to evaluation mode
model.eval()

all_preds = []
all_labels = []

# Disable gradients for evaluation
with torch.no_grad():
    for imgs, labels in val_loader:
        imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)
        outputs = model(imgs)
        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# Convert to numpy arrays
all_preds = np.array(all_preds)
all_labels = np.array(all_labels)

# 1️⃣ Overall accuracy
accuracy = (all_preds == all_labels).mean()
print(f"Validation Accuracy: {accuracy:.4f}")

# 2️⃣ Confusion matrix
cm = confusion_matrix(all_labels, all_preds)
print("Confusion Matrix:\n", cm)

# Plot confusion matrix
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=classes, yticklabels=classes)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# 3️⃣ Classification report (precision, recall, F1-score)
report = classification_report(all_labels, all_preds, target_names=classes)
print("Classification Report:\n", report)

